### ISSUE TITLE
Add Yahoo

### ISSUE THREAD

**Issue by nassimsb** [schmiedecker/unStalkMe#6]
1. Sieht man die Geräte die verbunden sind mit dem Account? Ja, aber nicht die Geräte, die schon lange verbunden sind.
2. werden Zugriffe geloggt? Bei Aktivitäten werden nur die Logins gespeichert, bleibt ein Gerät eingeloggt, werden die Zugriffe nicht gespeichert. 
3. Wie lange wirds gespeichert? ungefähr 90 Tage

**Comment by schmiedecker** [comment]
Thanks! Could you please provide links to the sources?

**Comment by nassimsb** [comment]
I can't create pull or link this issue:
https://github.com/schmiedecker/unStalkMe/issues/6#issue-1395045194
